server:
  port: 8100
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.107.237.2:3306/cqc?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  http:
    encoding:
      charset: utf-8
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    # ddl-auto: create 每次都新建表 update 更新数据 validate 验证标结构属性是否一致
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
